{% set name = "bitgov" %}
{% set version = "0.1.3" %}
{% set hash = "44a1bfddc64389d474de16b9d3e37501630b82b4f25da0b46434db754b923566" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python

about:
  home: https://github.com/jgphilpott/bitgov
  summary: An application layer protocol for the establishment of decentralized democracy.
  license: MIT
